[[build]]
  # 빌드 명령어 (정적 사이트이므로 빌드 불필요)
  command = "echo 'No build needed for static site'"
  
  # 배포할 디렉토리
  publish = "."

[[redirects]]
  # 기본 페이지를 Silicon 버전으로 리디렉션
  from = "/"
  to = "/index-silicon.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login-silicon.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/signup-silicon.html"
  status = 200

[[headers]]
  # 모든 경로에 대한 헤더 설정
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[headers]]
  # HTML 파일에 대한 캐싱 설정
  for = "/*.html"
  [headers.values]
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  # 정적 자산에 대한 캐싱 설정
  for = "/Silicon/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 404 페이지 설정
[[redirects]]
  from = "/*"
  to = "/Silicon/404-v1.html"
  status = 404