[build]
  command = ""
  publish = "."

[[redirects]]
  from = "/"
  to = "/index-silicon.html"
  status = 200
  force = true

[[redirects]]
  from = "/login"
  to = "/login-silicon.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/signup-silicon.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/Silicon/404-v1.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"

[[headers]]
  for = "/Silicon/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"